// AUTO-GENERATED by scripts/gen-covers.mjs — do not edit by hand.
// Lists the book slugs that have a real cover screenshot in
// public/images/books/. Re-run `node scripts/gen-covers.mjs` after
// adding or removing a cover.

export const COVERS = new Set<string>([
  "antologia-della-letteratura-araba-dalle-",
  "arabia-deserta",
  "arabia-felix",
  "breve-storia-dell-islam",
  "dormire-con-il-diavolo-come-washington-h",
  "gli-arabi-3000-anni-di-storia-di-popoli-",
  "i-partigiani-di-allah-dall-iran-all-arab",
  "i-sette-pilastri-della-saggezza",
  "ingolfato-come-l-arabia-saudita-ha-compr",
  "isolario-arabo-medioevale",
  "l-architettura-islamica-una-storia-mondi",
  "l-occhio-e-l-ago-saggio-sulle-mille-e-un",
  "la-bicicletta-verde-su-due-ruote-verso-l",
  "la-biciletta-verde",
  "la-mecca-rivelata-avventure-di-esplorato",
  "lawrence-d-arabia-e-l-invenzione-del-med",
  "le-mille-e-una-notte",
  "le-mu-allaqat-alle-origini-della-poesia-",
  "letteratura-araba",
  "letteratura-araba-contemporanea-dalla-na",
  "lo-scisma-della-mezzaluna-sunniti-e-scii",
  "lo-yemen-raccontato-dalle-scrittrici-e-d",
  "medio-oriente-uno-sguardo-antropologico",
  "orientalismo-l-immagine-europea-dell-ori",
  "purgatorio-arabo-il-tradimento-delle-riv",
  "ragazze-di-riad",
  "rose-d-arabia-racconti-di-scrittrici-del",
  "sabbie-arabe",
  "storia-dell-arabia-saudita",
  "storia-di-bilq-s-regina-di-saba",
  "sull-orlo-del-vulcano-il-caso-arabia-sau",
  "the-modern-arabic-short-story-shahrazad-",
]);
