// AUTO-GENERATED by scripts/gen-covers.mjs — do not edit by hand.
// Lists the book slugs that have a real cover screenshot in
// public/images/books/. Re-run `node scripts/gen-covers.mjs` after
// adding or removing a cover.

export const COVERS = new Set<string>([
  "lo-scisma-della-mezzaluna-sunniti-e-scii",
  "ragazze-di-riad",
  "the-modern-arabic-short-story-shahrazad-",
]);
