'use client';
import PanelBody from '@/app/components/PanelBody';
import Reveal from '@/app/components/Reveal';
import PhotoBackdrop from '@/app/components/PhotoBackdrop';
import { PANELS } from '@/app/[locale]/history/panels';

const CREDITS_PANEL = PANELS.find((p) => p.id === 'credits')!;

const INTRO: string[] = [
  'The relationship between the University of Bologna and the Arabian Peninsula now spans decades, with a partnership with the Sultanate of Oman inaugurated in the late 1970s and continuing to this day. The University of Bologna is one of Italy’s most important centres for the study of Arabian archaeology, and it is partly for this reason that it was selected to host, between 30 July and 1 August 2026, the 59th Seminar for Arabian Studies — the international conference promoted by the International Association for the Study of Arabia (IASA) on the historical, archaeological, ethnological and epigraphic research carried out across the Peninsula.',
  'This exhibition was conceived on the occasion of this internationally resonant event, as a chance to explore and present to the public the University of Bologna’s long scientific commitment in a region of the world that is often little — and poorly — known at our latitudes.',
  'The Arabian Peninsula remains an area little explored archaeologically and little known to the wider public, both in its geography and in its historical development. Tourism touches only a few cities and coastal zones, and desert tours are tightly organised and strongly managed by operators, concentrating and selecting for the public an infinitesimal part of the region’s cultural and environmental richness. In terms of archaeological output, although the Peninsula covers 3,100,922 km², publications are negligible compared with those on Iraq, Syria, Jordan, Lebanon, Egypt, Palestine, Israel, Turkey, Greece, Italy and Cyprus — which together do not reach the same territorial extent.',
  'This exhibition sets out to trace the historical-geographical coordinates of the Arabian Peninsula and to illustrate the scientific and highly technological approaches used by the University of Bologna to investigate past societies — in order to provide tools for interpreting the present more consciously, to highlight the cultural and commercial centrality of the Peninsula since antiquity, and to stimulate curiosity about the complex and creative relationship over time between people and environment in a region of extreme ecosystems but also of unexpected potential.',
];

const GEOGRAPHY: string[] = [
  'The Arabian Peninsula is a subcontinent forming the south-western extension of Asia, bounded by three seas: the Red Sea to the west, the Arabian Sea to the south-east and the Persian Gulf to the north-east. It lies exactly on the Tropic of Cancer, in the subtropical high-pressure zone that gives it a strongly arid climate. Its margins are studded with mountain ranges, particularly in the south between the far south of Saudi Arabia, south-western Oman and Yemen, while the entire central part is occupied for 600,000 square kilometres by the immense Rub‘ al-Khali desert, the “Empty Quarter”. A third of the total surface is covered by sand, generated by the erosion of rock under several factors — sudden temperature swings, abrupt and intense rains followed by rapid evaporation, and the action of sandstorms and of salt and gypsum crystals.',
  'The Peninsula comprises seven sovereign states: the Kingdom of Saudi Arabia, the Republic of Yemen, the Sultanate of Oman, the United Arab Emirates, the State of Qatar, the Kingdom of Bahrain and the State of Kuwait. All are hereditary monarchies except Yemen, the region’s only republic. This relative institutional homogeneity favours cooperation within the Gulf Cooperation Council (GCC), which promotes economic and political coordination among the region’s monarchies.',
  'The states of the Peninsula are highly heterogeneous in size and in demographic and economic weight. Saudi Arabia, capital Riyadh, occupies about 80% of the surface, borders almost all the others, and plays a central role in regional balances thanks to its hydrocarbon reserves and the presence of the holy cities of Mecca and Medina. To the south-west lies Yemen, capital Sana‘a, the most populous country after Saudi Arabia but also one of the most fragile politically and economically. In the south-east extends Oman, capital Muscat, controlling important outlets onto the Arabian Sea and the Gulf of Oman.',
  'Along the Persian Gulf coast cluster other small but influential states. The United Arab Emirates is a federation of seven emirates — Abu Dhabi, Ajman, Dubai, Fujairah, Ras al-Khaimah, Sharjah and Umm al-Quwain — and one of the region’s main economic and financial centres. Qatar, capital Doha, occupies a small peninsula projecting into the Persian Gulf. Further north, Kuwait, capital Kuwait City, lies between Saudi Arabia and Iraq; its strategic position at the northern end of the Gulf has long made it an important commercial node and a contested territory. Bahrain, finally, is the smallest state of the Peninsula, capital Manama — an archipelago of more than 30 islands, many uninhabitable.',
];

export default function Exhibition() {
  return (
    <article className="bg-petroleum-blue text-desert-sand">
      {/* Intro over a beach backdrop */}
      <section className="relative overflow-hidden">
        <PhotoBackdrop src="/images/photos/bir-hima-cattle.jpg" focal="center 45%" />
        <div className="relative z-10 max-w-6xl mx-auto px-6 py-20 md:py-28">
          <p className="text-xs tracking-[0.25em] uppercase text-desert-sand/60 mb-3">
            The Exhibition
          </p>
          <h1 className="font-display text-4xl md:text-6xl leading-[1.05] mb-10">
            Introduction to the exhibition and political geography
          </h1>

          <div className="max-w-prose space-y-5 text-lg leading-relaxed opacity-90">
            {INTRO.map((p, i) => (
              <Reveal key={i} delay={i * 0.05}>
                <p>{p}</p>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Geography over a coastal backdrop */}
      <section className="relative overflow-hidden">
        <PhotoBackdrop src="/images/photos/beach-rider.jpg" focal="center 42%" />
        <div className="relative z-10 max-w-6xl mx-auto px-6 py-16 md:py-20">
          <Reveal>
            <h2 className="font-display font-extrabold text-2xl md:text-3xl mb-6 text-desert-sand">
              Geography
            </h2>
          </Reveal>
          <div className="max-w-prose space-y-5 leading-relaxed opacity-95">
            {GEOGRAPHY.map((p, i) => (
              <Reveal key={i} delay={i * 0.05}>
                <p>{p}</p>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      <div className="max-w-6xl mx-auto px-6 pb-20 md:pb-28">
        <section
          id="credits"
          className="mt-4 pt-12 border-t border-desert-sand/20 scroll-mt-24"
        >
          <p className="text-xs tracking-[0.25em] uppercase text-desert-sand/60 mb-2">
            {CREDITS_PANEL.kicker}
          </p>
          <h2 className="font-display text-3xl md:text-4xl mb-8 text-desert-sand">
            {CREDITS_PANEL.title}
          </h2>
          <PanelBody panel={CREDITS_PANEL} />
        </section>
      </div>
    </article>
  );
}
