// History section content (English). Translated from the original Italian
// panel texts. Production notes, image placeholders and internal TODOs from the
// source documents have been removed. Kept as structured data here (rather than
// in the i18n message files) because the volume is large and the IT/AR locales
// are still pending translation.
//
// The Bronze Age and Iron Age subsections of the "history" panel were expanded
// from a fuller Italian draft ("Oltre il deserto: storie di popoli e scoperte"),
// adding burial archaeology, named coastal sites and the social-differentiation
// narrative that the original panel text only summarised.

export type Block =
  | { type: 'h'; text: string }
  | { type: 'p'; text: string };

export type Credit = { role: string; names: string[] };

export type Panel = {
  id: string;
  number: string;
  kicker: string;
  title: string;
  blocks?: Block[];
  credits?: Credit[];
  acknowledgements?: string;
};

export const PANELS: Panel[] = [
  {
    id: 'introduction',
    number: '01',
    kicker: 'Introduction',
    title: 'Introduction to the exhibition and political geography',
    blocks: [
      {
        type: 'p',
        text: 'The relationship between the Department of Archaeology of the University of Bologna and the Arabian Peninsula spans decades, with a partnership with the Sultanate of Oman inaugurated in the late 1970s and continuing to this day. The University of Bologna is one of Italy’s most important centres for the study of Arabian archaeology, and it is partly for this reason that it was selected to host, between 30 July and 1 August 2026, the 59th Seminar for Arabian Studies — the international conference promoted by the International Association for the Study of Arabia (IASA) on the historical, archaeological, ethnological and epigraphic research carried out across the Peninsula.',
      },
      {
        type: 'p',
        text: 'This exhibition was conceived on the occasion of this internationally resonant event, as a chance to explore and present to the public and the academic community the University of Bologna’s long scientific commitment in a region of the world that is often little — and poorly — known at our latitudes.',
      },
      {
        type: 'p',
        text: 'The Arabian Peninsula remains an area little explored archaeologically and little known to the wider public, both in terms of its geography and its historical development. Tourism touches only a few cities and coastal zones, and desert tours are tightly organised and strongly managed by operators, concentrating and selecting for the public an infinitesimal part of the region’s cultural and environmental richness. In terms of archaeological scientific output, although the Peninsula covers an area of 3,100,922 km², publications are negligible compared with those concerning Iraq, Syria, Jordan, Lebanon, Egypt, Palestine, Israel, Turkey, Greece, Italy and Cyprus — which together do not reach the same territorial extent.',
      },
      {
        type: 'p',
        text: 'This exhibition sets out to trace the historical-geographical coordinates of the Arabian Peninsula and to illustrate the scientific and highly technological approaches used to investigate past societies — in order to provide tools of knowledge for interpreting the present more consciously, and to stimulate curiosity about the complex and creative relationship, over time, between people and environment in a region of extreme ecosystems but also of unexpected potential.',
      },
      {
        type: 'p',
        text: 'The Arabian Peninsula is a subcontinent forming the south-western extension of Asia, bounded by three seas: the Red Sea to the west, the Arabian Sea to the south-east and the Persian Gulf to the north-east. It lies exactly on the Tropic of Cancer, in the subtropical high-pressure zone that gives it a strongly arid climate. The margins of the Peninsula are studded with mountain ranges, particularly in the south between the far south of Saudi Arabia, south-western Oman and Yemen, while the entire central part is occupied for 600,000 square kilometres by the immense Rub‘ al-Khali desert, the “Empty Quarter”. A third of the total surface is covered by sand, generated by the erosion of rock under strong mechanical pressure from several factors — sudden temperature swings, abrupt and intense rains followed by rapid evaporation, and the action of sandstorms and of salt and gypsum crystals.',
      },
    ],
  },
  {
    id: 'history',
    number: '02',
    kicker: 'Historical excursus',
    title: 'A historical journey across the Arabian Peninsula',
    blocks: [
      {
        type: 'p',
        text: 'From the first crossing of the Rub‘ al-Khali in the 1920s to the most modern technologies such as satellite radar, numerous expeditions have uncovered the remains of ancient landscapes and settlements now buried beneath the sands, revealing a past rich in life. The Arabian Peninsula is often imagined as a vast, empty and inhospitable desert. Its most ancient history, however, tells of a far more variable scenario — a mosaic of different environments, crossed and inhabited by human groups since very remote times.',
      },
      { type: 'h', text: 'Palaeolithic' },
      {
        type: 'p',
        text: 'In archaeology, the period called “Prehistory” recounts the long journey of human beings before the invention of writing. For the Arabian Peninsula, this means studying the communities that lived before the 8th century BCE.',
      },
      {
        type: 'p',
        text: 'The Peninsula is often imagined as a great desert. Yet for millennia its climate was governed by the monsoons of the Indian Ocean. Phases of extreme aridity alternated with warm, humid periods during which the desert gave way to rivers, lakes and savannahs populated by hippopotamuses and elephants: an extraordinary landscape that scientists call “Green Arabia”.',
      },
      {
        type: 'p',
        text: 'Situated between Africa, Europe and Asia, the Peninsula was a fundamental geographic bridge for the first human migrations out of the African continent. Of these ancient hunter-gatherers, what mainly survives are stone tools (bifaces, flakes and points). The only skeletal evidence of hominins known to date comes from the site of Al Wusta 1 in Saudi Arabia, where a finger bone was found associated with around 400 lithic artefacts, dated to between 95,000 and 85,000 years ago.',
      },
      {
        type: 'p',
        text: 'In the Middle Palaeolithic, sophisticated lithic technologies appear, such as the Nubian Levallois — a knapping method that allowed the core to be prepared and flakes or points of predetermined shape to be obtained. This technology is documented above all in Dhofar, on the Nejd plateau, where hundreds of surface sites have been recorded.',
      },
      { type: 'h', text: 'Neolithic' },
      {
        type: 'p',
        text: 'With the end of the last glaciation and the beginning of the Holocene, between 10,000 and 6,000 years ago, Arabia experienced its last great humid phase.',
      },
      {
        type: 'p',
        text: 'In the Neolithic, communities no longer lived solely by hunting, fishing and gathering: they also introduced the herding of cattle, sheep and goats. This change, however, did not everywhere lead to stable farming villages as in other regions of Western Asia, such as Mesopotamia. Depending on the area, herding was integrated with hunting, fishing, shellfish gathering and seasonal movements between coast, interior and mountains. This mixed economy was not a “delay” relative to agriculture, but an adaptive choice consistent with the Arabian environment.',
      },
      {
        type: 'p',
        text: 'Some glimpses of daily life are evocatively documented by rock art, in which central and northern Arabia are particularly rich (e.g. the Camel Site, Jubbah/Jebel Oraf, Bir Hima). The engraved images of bovids, gazelles, oryx, ibex, dogs, ostriches and human figures suggest landscapes richer in fauna than today, documenting aspects of social life, ritual practices and the environment of the time.',
      },
      {
        type: 'p',
        text: 'Among the most fascinating discoveries of recent years are the so-called “mustatil”, from the Arabic for “rectangle”: large rectangular stone structures built between 7,000 and 6,000 years ago — genuine monumental open-air enclosures linked to ritual practices such as the selected deposition of animal remains, especially cattle.',
      },
      {
        type: 'p',
        text: 'As partly anticipated, between 8,000 and 5,000 years ago humidity decreased and the climate became progressively more arid again. The northern areas felt this change first, while southern Arabia maintained more favourable conditions for longer. Communities responded in different ways: some strengthened pastoral mobility, others concentrated around springs, and still others specialised in exploiting marine resources, increasing their familiarity with the ocean and opening the way to navigation.',
      },
      {
        type: 'p',
        text: 'Between the 5th and 4th millennia BCE, eastern Arabia came into contact with Mesopotamia. Imported painted Ubaid-type pottery has been found at several Gulf sites. In Kuwait, boat models, depictions of vessels and bitumen bearing reed impressions indicate nautical skills and maritime exchange.',
      },
      {
        type: 'p',
        text: 'At several sites, from the north to the south of the Peninsula, the use of grinding stones to process local wild plants for food is documented. This is not yet true agriculture. The oldest macro-botanical remains of dates linked to human consumption are concentrated in the Arabian Gulf area, at sites such as Dalma Island and Marawah, dating to around 5000 BCE. The gathering and consumption of wild dates begins in the Neolithic, while the morphological traits of the cultivation and domestication of the date palm consolidate only between the 4th and 3rd millennia BCE, in the Bronze Age.',
      },
      {
        type: 'p',
        text: 'At the same time, signs of growing social complexity emerge. In the north of the Peninsula, the anthropomorphic stelae found near al-‘Ula and Ha’il point to new forms of representation of the body, of memory and perhaps of collective identity.',
      },
      {
        type: 'p',
        text: 'At the end of the Neolithic, between the late 5th and 4th millennia BCE, a growing regionalisation can be observed: contacts between groups from different environments seem to diminish, while local traditions become more pronounced. From this point on, south-eastern Arabia follows its own developments, distinct from those of the great civilisations of the East — even though the new political systems born in Mesopotamia, Iran and the Indus Valley also stimulated a strengthening of the exchange economy in Arabia.',
      },
      { type: 'h', text: 'Bronze Age' },
      {
        type: 'p',
        text: 'The Bronze Age in Arabia represents a crucial phase in the formation of the region’s complex societies. Culturally, four main periods are identified: Hafit (3100–2700 BCE), Umm an-Nar (2700–2000 BCE), Wadi Suq (2000–1600 BCE) and finally the Late Bronze Age (1600–1250 BCE).',
      },
      {
        type: 'p',
        text: 'The Arabian Peninsula was integrated into the trade system of the Near East, as documented in Sumerian and Akkadian tablets. These name Magan (Oman) and Dilmun (Bahrain) as key places for the supply and trade of copper in the 3rd and 2nd millennia BCE. The Ur tablets record that tonnes of raw copper entered the royal warehouses, where it was weighed and then distributed to local smiths to produce bronze (an alloy of copper and tin). During the Akkadian Empire, control of the trade routes within the Persian Gulf became a strategic priority — to the point that rulers organised military campaigns against Magan. Millennia later, modern archaeology in Oman and the United Arab Emirates has confirmed what was written on the clay tablets: alongside the excavation of extensive copper-extraction and -working sites (such as Al-Maysar or Sohar), the copper ingots found in Mesopotamia bear a chemical signature matching the ore deposits of the Omani mountains. The Arabian coasts were a hub between Mesopotamia, Iran and the Indus Valley Civilisation — like the island of Failaka in present-day Kuwait, Tarut in Saudi Arabia and Umm an-Nar in the Emirates.',
      },
      {
        type: 'p',
        text: 'The absence of evidence for a centralised administrative system and complex urban networks — as seen instead in contemporary neighbouring regions, for example in the Near East — has led scholars to favour the hypothesis of less hierarchical, more fluid social organisations. The monumental, multiple burials convey a strong collective consciousness in which the relationship with the ancestors and with the territory is a central element of social and geographic identity. In the oases, such as Hili (UAE), which has yielded a vast archaeological deposit, agriculture was practised thanks to the construction of a special microclimate created by the date palm and to water management in the form of channels or dams according to the basins available. The coasts, by contrast, attest to fishing and even long-distance maritime trade. The site of Qal‘at al-Bahrain (Bahrain), capital of the legendary Dilmun civilisation, served as a “free port” and a place for experimenting with commercial accounting, as attested by the circular stone seals. The discovery of pieces of bitumen bearing the impressions of reeds and ropes, also at the site of Ras al-Jinz (Oman), has made it possible to reconstruct the appearance of vessels suited to ocean navigation.',
      },
      {
        type: 'p',
        text: 'Funerary architecture is among the most telling testimonies of the period. Tumuli, necropolises and monumental tombs — such as those of the Awam temple cemetery at Marib, where thousands of graves bear funerary stelae with stylised portraits and dedicatory inscriptions — reveal an almost obsessive concern with eternal memory and with the name of the deceased. A striking phenomenon is that of the so-called empty tombs, or cenotaphs, found at sites such as Baraqish: monuments raised for merchants who died on the long journeys along the Incense Road and whose bodies could not be brought home, showing that memory and honour mattered more than the physical presence of the body. The tombs also acted as landmarks, marking boundaries and routes across the desert and turning the territory into a “cultural landscape” in which memory, trade and identity were interwoven.',
      },
      {
        type: 'p',
        text: 'The typology of burials evolves over time: from collective tombs, indicative of clan identity, the period shifts towards individual burials linked to status, prestige or personal wealth — a sign of growing social differentiation that nonetheless never produced centralised states or rigid hierarchies. Grave goods, exotic objects and secondary burials point to elaborate rituals that could last months, making the tombs instruments of social and political cohesion as much as means of consolidating economic relations and marking the land.',
      },
      {
        type: 'p',
        text: 'The coastal sites reveal how urbanised and interconnected these societies could be. Qal‘at al-Bahrain, capital of the legendary Dilmun civilisation, grew into a fortified “free port” and pivot between Mesopotamia and the Indus, where circular soapstone seals and a standardised Dilmun weight system attest to advanced notions of property and mercantile accounting. The island of Umm an-Nar, eponymous site of the culture that spread across northern and eastern Arabia between 2700 and 2000 BCE, specialised in smelting and exporting copper from the interior mountains and is famous for its monumental circular collective tombs in finely worked stone. At Tell Abraq, occupied continuously from the Bronze to the Iron Age, an imposing circular fortress of stone and mud brick protected accumulated wealth and yielded finds from across the known ancient world — cuneiform seals, Indus Valley pottery and ivory.',
      },
      {
        type: 'p',
        text: 'The Bronze Age is also characterised by the domestication and spread of the dromedary (around the 10th century), which revolutionised the possibilities of movement across the desert. Pastoralism was still widely practised. New techniques in food preservation, such as smoking and drying, were also developed, allowing food to be transported on long desert journeys. These technological innovations enabled merchants and herders to move across Arabia — between oases, coastal sites and inland routes — creating more extensive and stable networks of interaction. Mobility thus became a genuine organising principle for the better exploitation of the territory.',
      },
      {
        type: 'p',
        text: 'Towards the close of the Bronze Age, in the transition to the Iron Age, the region underwent a progressive aridification, with declining rainfall caused by a shift in the path and intensity of the monsoon currents.',
      },
      { type: 'h', text: 'Iron Age' },
      {
        type: 'p',
        text: 'The Iron Age, generally dated between the 1st millennium BCE and the advent of Islam, marks a period of consolidation of social and political structures in Arabia. One of the most evident features of this period is settlement stability in some regions: the south of the Peninsula sees the emergence of urban aggregations — tribal confederations led by a ruler, such as Saba, Qataban, Hadramawt and Ma’in — which gained control over trade routes and local resources, while in northern Arabia they concentrated in the oases and the more fertile agricultural areas. In southern and north-western Arabia a monumentality of buildings and temples can be observed that is rare in the eastern part, where a village-based settlement organisation prevailed instead.',
      },
      {
        type: 'p',
        text: 'The monumental necropolises take on an even more prominent role as instruments of political and social identity. The Awam temple cemetery at Marib, with its thousands of tombs, is emblematic: funerary stelae with stylised portraits and dedicatory inscriptions point to an extreme attention to the memory and prestige of the dead, often tied to influential families or high-ranking merchants. Such monuments also consolidated the kingdoms’ presence on the land and marked symbolic boundaries, turning the tombs into veritable “lighthouses” of the desert landscape. Alongside tombs holding real bodies, cenotaphs continued to be built for merchants who died on trade journeys — empty buildings that again placed the memory and recognised role of the deceased above the body itself.',
      },
      {
        type: 'p',
        text: 'External influences — from the Levant and Mesopotamia, and later from the Hellenistic and Roman worlds — were assimilated and reinterpreted without overturning local structures. Some loculus or kokhim tombs echo foreign traditions yet were absorbed into local funerary practice, producing an original heritage adapted to Arabian conditions. Cultural interaction did not imply subordination: the Arabian kingdoms remained the protagonists of their own choices.',
      },
      {
        type: 'p',
        text: 'During the Iron Age, Arabia consolidated trade routes with connections crossing the entire Near East and reaching as far as the Mediterranean. The oasis of Dadan (al-‘Ula, Saudi Arabia) was the northern terminal of an overland route linking Yemen with Palestine. The Arabian kingdoms controlled the trade in precious goods — frankincense, myrrh and spices — along caravan routes. The production area for the highest-quality frankincense and myrrh lay between north-eastern Yemen and south-western Oman, in the present-day Dhofar region, favoured by the seasonal monsoons. Navigation became more frequent towards the north-west: around the 1st century BCE an anonymous Greek author compiled a portolan known as the Periplus of the Erythraean Sea, a commercial guide for sailing and trading between the Arabian Peninsula, Africa and India. Recent Greek and Roman influences were assimilated and reinterpreted by the Arabian populations without overturning local structures: around 230 BCE, the king of Gerrha, Abiyata’, minted coins portraying himself as a Macedonian sovereign.',
      },
      {
        type: 'p',
        text: 'The development of writing in Arabia occurred during the Iron Age: between the 10th and 8th centuries BCE a South Arabian alphabet became established, while the first North Arabian graffiti are dated to the 6th–4th centuries BCE. Although graffiti and small statuettes already attested a complex religiosity in earlier periods, epigraphic sources allow us to recognise a multitude of deities celebrated by the local populations — with a strong personal relationship between the worshipper and the deity, each with specific characteristics and dedicated places of worship, whether large buildings or natural recesses.',
      },
      {
        type: 'p',
        text: 'A significant trait of the Iron Age is also its cultural preparation for the transition to the Islamic era. Although pagan rituals continued for centuries, funerary practices gradually tended towards simplification, with fewer grave goods and a growing attention to equality before death — a sensibility that anticipates the uniform practices of Islam. Taken together, the tombs of the Iron Age tell a story of prestige, memory and cohesion, attesting both to the participation of the Arabian kingdoms in complex cultural and economic networks and to their will to consolidate local identity and the bond with the territory.',
      },
      { type: 'h', text: 'Islam' },
      {
        type: 'p',
        text: 'In the 6th century the Peninsula was characterised by the absence of a unified political structure, fragmented into a multitude of political entities.',
      },
      {
        type: 'p',
        text: 'To the north, the Near East was divided between the Byzantine and Sasanian empires, competing not only for territorial control but also on the cultural and religious plane. In the border territories, tribes such as the Ghassanids and the Lakhmids — who would later play a fundamental role in the spread of Islam — acted as intermediaries with the Arab world. Cities such as Mecca and Yathrib gained growing importance as commercial and religious nodes. Mecca in particular was home to the Ka‘ba, a cube-shaped sanctuary that housed the statue of the god Hubal and was an object of pilgrimage. The religious landscape was remarkably varied: alongside local polytheistic and animist cults, there were Jewish, Christian and Zoroastrian communities.',
      },
      {
        type: 'p',
        text: 'The prophet Muḥammad was born around 570; he belonged to the Hashim clan, a branch of the Quraysh, the dominant tribe of Mecca. Around 610, during a periodic retreat dedicated to meditation and reflection, he began to have religious experiences. These divine revelations were later collected in the Qur’an, the sacred text of Muslims. Because of his preaching he was expelled from his clan, and in 622 he moved to the oasis of Yathrib, known as Medina, from the Arabic madinat an-nabi, “the city of the Prophet”. With the Prophet’s migration, known as the Hijra, Muḥammad became the leader of the umma, a cohesive community founded on bonds of faith rather than blood — marking a break with tribal ties. Within a few years Muḥammad managed to consolidate his authority in the western regions of the Peninsula, while the northern and eastern regions, Yemen, the Hadramawt and Oman began to respond positively to his message.',
      },
      {
        type: 'p',
        text: 'On Muḥammad’s death in 632, his first successors — known in Islamic tradition as caliphs (khalifa: “successor/representative”) and called the “Rightly Guided” (rashidun) — launched a policy of repressing the secessionist impulses of the Bedouin tribes, who held that their agreements with the Muslims had lapsed on the Prophet’s death. Campaigns of expansion unexpectedly led to the formation of a vast empire stretching from the Iberian Peninsula to Central Asia, partly exploiting the political weaknesses of the Byzantine and Sasanian empires. Under the Umayyad (661–750) and Abbasid (750–1258) caliphates, the political centre shifted to Damascus and Baghdad respectively. The Arabian Peninsula remained largely on the margins of the main political dynamics of the Islamic empires, but retained a central role above all on the religious and commercial plane. The cities of Mecca and Medina became fundamental poles of Islamic pilgrimage.',
      },
      {
        type: 'p',
        text: 'Coastal ports such as Suhar (Oman), Aden (Yemen) and Jeddah (Saudi Arabia) were involved in Indian Ocean trade, connecting East Africa, South Asia and the Gulf, while inland communication routes continued to favour trade, pilgrimage and tribal alliances. In several localities of the Hejaz, local dynasties settled, giving rise to small principalities, or emirates, while elsewhere autonomous tribal structures persisted.',
      },
      {
        type: 'p',
        text: 'In the 12th century, the Ayyubids of Egypt invaded Yemen, taking control of several local dynasties. The Rasulid sultanate was founded by the descendants of the Ayyubid emir ‘Alī ibn Rasūl and extended along the southern coast of Yemen as far as Dhofar in Oman, marking the most flourishing era of the area in Islamic history.',
      },
      {
        type: 'p',
        text: 'The destruction of Baghdad in 1258 and the killing of Sultan al-Musta‘sim by the Mongols brought about the fall of the Abbasid caliphate. By contrast, the defeat of the Mongols by the Egyptian armies conferred unprecedented prestige on the Mamluk sultans, who became the dominant power in the Hejaz during the 14th and 15th centuries.',
      },
      {
        type: 'p',
        text: 'At the beginning of the 16th century, having defeated the Mamluk armies, the Ottoman sultan Selim proclaimed the Hejaz and its holy cities part of the Ottoman domains. In those same years Portuguese ships reached the Indian Ocean and the Red Sea, threatening to interrupt the spice trade from India to Europe and permanently damaging the region’s economy. Coastal Arabia gradually came into direct contact with other European maritime powers as well — the Netherlands, England and France — which, in the wake of the Portuguese, were launching their commercial expansion in the Indian Ocean.',
      },
      {
        type: 'p',
        text: 'In the 18th century, a religious reform movement emerged in the Najd led by Muhammad ibn Abd al-Wahhab, who advocated a return to a rigorous form of Islam. The alliance between this movement and the Al Sa‘ud family gave rise to a new political entity destined to play a decisive role in the following centuries. Despite the defeats suffered at the hands of the Ottomans, this alliance managed to consolidate its position over time.',
      },
      {
        type: 'p',
        text: 'In the 19th and early 20th centuries, the Arabian Peninsula was drawn into European expansionist dynamics, in particular the British, which aimed to control strategic routes and areas. The collapse of the Ottoman Empire after the First World War inaugurated a period of political reorganisation and centralisation of power: Yemen came under the control of Yaḥyā; the Kingdom of Saudi Arabia, which encompassed much of the Peninsula, was proclaimed by Ibn Saud in 1932; the rest became a British protectorate.',
      },
      {
        type: 'p',
        text: 'The discovery of oil marked the last profound transformation. Over the course of the 20th century, energy resources made Saudi Arabia and the other Gulf states key players in the global economy. Oil revenues fuelled rapid modernisation, leading to the construction of complex state apparatuses, infrastructure and education systems. At the same time, specific political and social models took hold in the newborn states, often based on a balance between tradition and innovation.',
      },
    ],
  },
  {
    id: 'aflaj',
    number: '03',
    kicker: 'Living in extreme environments',
    title: 'Aflaj and oases',
    blocks: [
      {
        type: 'p',
        text: 'The Peninsula lies between two different monsoonal climate systems, the North Atlantic and the Indian Ocean. The combination of palynological and sedimentary data suggests that, after a prolonged humid period, from around 4000 BCE there was a gradual but consistent decline in summer rainfall, caused by the southward retreat of the northern limit of the Indian Ocean monsoon. Although aridity is a common condition across the Peninsula, some areas have particular ecological characteristics: the southernmost tip of Oman and part of Yemen are still subject to the monsoon during the summer season, producing a temporary green cover and the formation of seasonal watercourses (wadis), sometimes of great volume. Near the sites of Ma’layba and al-Midamman (Yemen), the first diversion dams and channels were created to intercept the seasonal flooding of the wadis and redistribute it to the fields.',
      },
      {
        type: 'p',
        text: 'The creation of a system for regulating and supplying water is a key element for survival in areas subject to extreme aridity. Elsewhere in the Arabian Peninsula, gently sloping underground channels were designed to carry water for kilometres from aquifers at the foot of the mountains, preventing it from evaporating under the desert sun, and equipped with shafts for inspection and maintenance. The origin and authorship of this hydraulic system is debated in the literature, given its close resemblance to the Persian qanats.',
      },
      {
        type: 'p',
        text: 'The Aflaj irrigation systems (aflaj is the plural of falaj), typical of Oman, represent one of the most extraordinary testimonies of how human ingenuity managed to shape an environment as hostile as that of the Arabian Peninsula and to create a cultural landscape. Precisely for their exceptional historical, engineering and cultural value, in 2006 UNESCO inscribed five of these channels on the World Heritage List, elevating them to a symbol of a millennia-old tradition still widespread throughout Oman. To this day more than 3,000 aflaj are still active in the Sultanate.',
      },
      {
        type: 'p',
        text: 'The term falaj derives from an Arabic root meaning “to divide into parts”, a concept that perfectly expresses the dual nature of this system: a physical structure for channelling water and, at the same time, a refined model of social distribution. Although the structures visible today date predominantly to around 500 CE, various archaeological evidence suggests early experiments as far back as the Bronze Age. UNESCO recognition, however, does not merely celebrate the technical skill of this ancient hydraulics, but rewards above all the sophisticated system of community management that has ensured its survival over the centuries. In a context where water is the most precious resource, local communities developed a distribution model based on the utmost fairness and mutual dependence. The irrigation turns due to each landowner were calculated with extreme precision, historically based on observing the stars at night and using sundials by day. The management and maintenance of the channel were — and still are — entrusted to an elected administrator, charged with mediating and ensuring respect for the shared rules.',
      },
      {
        type: 'p',
        text: 'The strategic value of the aflaj is also attested by the defensive architecture surrounding them: along their course it is not uncommon to spot watchtowers and fortifications, erected in the past to protect the waterways from raids and sabotage. The five systems specifically protected by UNESCO — including the famous Falaj Daris and Falaj al-Khatmeen — are not disused archaeological relics but fully operational infrastructure. They continue to form the backbone of Omani agriculture, offering a concrete and current example of sustainable water-resource management.',
      },
      {
        type: 'p',
        text: 'The oases of ancient Arabia were not simply isolated green refuges in the desert, but complex artificial ecosystems, nerve centres of political power and crucial nodes of international trade. The development of this extraordinary technological innovation belongs to the 3rd millennium BCE. At the heart of this ecosystem is the date palm (Phoenix dactylifera), capable of altering the environment in every respect: thanks to its dense canopy, the palm creates a cooler, more humid local microclimate, shielding the ground from extreme evaporation and allowing the cultivation beneath it of cereals and vegetables otherwise impossible to grow in hyper-arid climates, such as wheat and barley. Exemplary in this regard is the site of Hili 8, in the United Arab Emirates, whose extraordinary stratigraphic continuity covers the entire Bronze Age, documenting the adoption of agriculture — in particular an integrated polyculture — and the stability of this humanised landscape.',
      },
      {
        type: 'p',
        text: 'This human and productive environment could not, however, have existed without the introduction of increasingly complex engineering solutions for managing water and irrigation. Because the cultivation of the date palm and the very development of the oasis required a constant water supply, the ability to channel and distribute water became the true trigger for social complexity in the region. Managing such a precious and scarce resource imposed a rigorous collective organisation, accelerating social stratification, bureaucratisation and the emergence of centralised authorities responsible for its control.',
      },
      {
        type: 'p',
        text: 'Consequently, the oases soon became nerve centres of agricultural storage and political administration, protected by imposing fortification works and monumental architecture — as attested by the construction of circular mud-brick towers, characterised by a massive perimeter wall, compartmentalised internal rooms intended for storing food surpluses and, at the centre, a deep water well to guarantee the community’s water autonomy. In north-western Arabia, the oases developed imposing curtain walls that in some cases extended for kilometres. These structures, which appeared at the beginning of the Bronze Age and then expanded significantly during the Iron Age, had the dual function of protecting the settled communities from external raids and of strictly delimiting the functional areas of the settlement — separating agricultural space from residential and funerary space.',
      },
      {
        type: 'p',
        text: 'Beyond serving as fortresses and centres of production, the strategic position and availability of supplies made the oases obligatory crossroads for the caravan routes, integrating them firmly into the circuits of continental trade. From meeting points between different communities and local markets, they evolved into genuine long-range commercial hubs. This global openness and the importance of the oases in the exchange networks of the time are amply confirmed by the archaeological materials recovered from excavations, where the discovery of pottery fragments and beads typical of the civilisations of Mesopotamia and the Indus Valley demonstrates how deeply interconnected these desert centres were with the greatest empires and cultures of the ancient world.',
      },
    ],
  },
  {
    id: 'history-of-studies',
    number: '04',
    kicker: 'History of research',
    title: 'A history of studies and the UniBo excavations',
    blocks: [
      {
        type: 'p',
        text: 'Modern archaeology in the Arabian Peninsula began in the mid-1950s, thanks to the pioneering systematic campaigns conducted by a Danish research team at the invitation of the governmental institutions of several Gulf countries. In the 1950s and 1960s, for small and institutionally fledgling countries such as Kuwait and Qatar, inviting foreign archaeologists was not only a scientific choice. Investigating their own roots helped to build a shared historical memory and to strengthen national identity — precisely as oil was transforming their society and their international role forever. International collaborations remain very active in the area today, with the exception of Yemen, where political instability and recent conflict have interrupted most fieldwork.',
      },
      {
        type: 'p',
        text: 'The history of archaeology in the Arabian Peninsula is also a history of women: at many key moments in the building of this field of study — especially in the Gulf, in Oman, in the Emirates and today also in Saudi Arabia — women were not marginal figures but protagonists in founding research traditions, in directing missions, in the study of materials, in bioarchaeology and in the institutional management of heritage. Among the most significant names are Karen Frifelt, Beatrice de Cardi, Theresa Howard-Carter and Margarethe Uerpmann. Even before modern archaeology, a phase marked by travels, surveys, antiquarianism, epigraphy, historical geography and early scientific explorations saw the presence of figures such as Lady Anne Blunt, Gertrude Caton-Thompson, Elinor Wight Gardner and Freya Stark.',
      },
      {
        type: 'p',
        text: 'Bahrain was the first Gulf country to host a modern, systematic archaeological campaign. In 1953, a Danish team led by Peter Glob and Geoffrey Bibby arrived on the island to investigate the traces of Dilmun, the kingdom known from Mesopotamian sources as a hub of trade between the Gulf, Mesopotamia and the Indo-Iranian world. To give stability to this research, the permanent French Archaeological Mission was founded in 1977 and has, for almost fifty years, excavated continuously at the Bahrain Fort site, Qal‘at al-Bahrain. Bahrain, historically open to exchange and international contacts, has continued to support the presence of foreign researchers and collaboration with scientific institutions from various countries.',
      },
      {
        type: 'p',
        text: 'In the United Arab Emirates, the history of modern archaeology is intertwined with the very birth of the nation. In 1959, before independence from the United Kingdom, a British oil company invited the Danish archaeological school to investigate a monumental complex on the island of Umm an-Nar, in Abu Dhabi. Sheikh Zayed bin Sultan Al Nahyan, future founder of the UAE, immediately grasped the value of studying the past, and from that moment the Emirates have continued to welcome foreign missions, hosting Iraqi, French, German, Italian and Australian teams from the 1970s and 1980s onwards.',
      },
      {
        type: 'p',
        text: 'Kuwait opened its doors to foreign missions in 1958, when the local government invited the Danish expedition already active in Bahrain. Attention focused almost immediately on the island of Failaka, strategically positioned off the coast of Kuwait City. Here the Danish archaeologists recognised a key outpost of the Dilmun civilisation during the Bronze Age and, later, an important Hellenistic settlement equipped with a fortress in the Greek tradition. From that moment Kuwait has remained a stable partner of international research, welcoming over time French, Polish, Slovak, Georgian and Italian missions.',
      },
      {
        type: 'p',
        text: 'The history of foreign archaeology in Qatar began in 1956, when the country invited the Danish team led by Peter Glob. This first season of research (1956–1965) made it possible to document numerous prehistoric settlements in the interior and the petroglyphs of Jebel Jusasiyah. After independence, between 1976 and 1982, a new phase of investigations was conducted by French archaeologists. In the early 2000s, with the birth of the Qatar Museums Authority and a broad programme of cultural investment, the country further strengthened its collaboration with international universities and missions. The focus of much research became Al Zubarah, a fortified coastal city of the 18th century linked to the pearl trade, today a UNESCO site and a symbol of Qatar’s historical narrative.',
      },
      {
        type: 'p',
        text: 'Yemen was already known in antiquity for the wealth of its pre-Islamic kingdoms, including that of Saba — which is why Pliny the Elder called it Arabia Felix. Through its echoes in literature, the country aroused the interest of travellers and scholars as early as the 18th century, among them Carsten Niebuhr. The first modern archaeological missions, however, began in the early 1950s, with the American expeditions led by Wendell Phillips in the Marib area. After a phase of political instability, from the 1980s Yemen experienced a new season of international research. In 1980 the country ratified the UNESCO convention and welcomed French, German and Italian missions. Unlike many neighbouring Gulf countries, however, this history of collaboration has been interrupted: the conflict that began in 2014 forced foreign missions to suspend fieldwork and exposed many archaeological sites to severe risk.',
      },
      {
        type: 'p',
        text: 'For decades Saudi Arabia remained a context difficult to access for foreign missions. After a first opening in the mid-1970s, the real turning point came in the early 2000s thanks to a historic agreement with France. In 2003 a Franco-Saudi mission began excavating the site of Hegra, which a few years later would become the country’s first UNESCO site. This result encouraged the opening to new international collaborations: from 2009 teams arrived from various countries, including Italy, with the University of Naples “L’Orientale” engaged at the oasis of Dumat al-Jandal. In recent years, and particularly since 2016, thanks to the Vision 2030 programme, this opening has expanded further, within a national strategy seeking to diversify the economy by investing in tourism, culture and heritage. Today Saudi Arabia supports major archaeological projects in areas such as AlUla, transforming long-inaccessible regions into important international research laboratories.',
      },
      { type: 'h', text: 'Oman' },
      {
        type: 'p',
        text: 'In the Sultanate of Oman, modern archaeological research developed above all from the 1970s, in parallel with the construction of the national institutions dedicated to heritage. The establishment in 1976 of a ministry for Omani heritage — later transformed into the current Ministry of Heritage and Tourism — accompanied a new season of protection, research and enhancement. In this context, archaeologists such as Serge Cleuziou and Maurizio Tosi played a decisive role, helping to define the archaeology of south-eastern Arabia as an international field of research. At Bat, investigated by Karen Frifelt’s Danish missions, one of the most important monumental landscapes of eastern Arabia emerged, with towers, settlements and necropolises of the 3rd millennium BCE; Oman itself is identified with the ancient land of Magan, known from Mesopotamian sources for copper and for contacts with Mesopotamia and the Indus Valley. Today the Sultanate has five UNESCO sites — Bahla, Bat-Al-Khutm-Al-Ayn, the Land of Frankincense, the aflaj irrigation systems and the ancient city of Qalhat — which convey the chronological and geographic breadth of its heritage.',
      },
      { type: 'h', text: 'The history of the University of Bologna excavations' },
      {
        type: 'p',
        text: 'The research of the University of Bologna has focused on the Sultanate of Oman, above all on prehistory and protohistory, with particular attention to Neolithic and Bronze Age communities, to the relationships between coast and interior, and to the exchange networks of the Indian Ocean.',
      },
      {
        type: 'p',
        text: 'This history is part of a broader Italian tradition of collaboration with the Omani authorities, begun in the 1970s and supported by universities, research centres, ISMEO (International Association for Mediterranean and Oriental Studies) and the Ministry of Foreign Affairs. Within this framework, Oman became a privileged laboratory for studying the adaptation of human communities to coastal, mountainous, desert and oasis landscapes. A fundamental starting point is represented by the research of Maurizio Tosi (1944–2017). Having arrived in Oman in 1975, Tosi began investigations in 1977 into the Neolithic fishers of Ras al-Hamra, in the Muscat area. Tosi was then affiliated with the Istituto Universitario Orientale of Naples, before his move to the University of Bologna — which would later establish itself as one of the principal Italian centres for archaeological research in south-eastern Arabia.',
      },
      {
        type: 'p',
        text: 'From 1985 this line of research developed into the Joint Hadd Project, an Italian-French collaboration directed by Maurizio Tosi and Serge Cleuziou and dedicated to the Ja‘lān area, between Ras al-Hadd and Al Ashkarah. The project — linked to ISMEO, the French CNRS and the University of Bologna — investigated the evolution of settlement from the early-middle Holocene to the Islamic era, with particular attention to the relationships between coastal communities, inland regions and the exchange networks of the Indian Ocean.',
      },
      {
        type: 'p',
        text: 'At Ra’s al-Jinz, the excavations documented a settlement of the second half of the 3rd millennium BCE, with craft activities and materials originating from the Indus and Mesopotamia. At Ra’s al-Hadd, by contrast, the settlement of HD-6, investigated from 1995 under the direction of Maurizio Cattani, brought to light a settlement of the first half of the 3rd millennium BCE, with mud-brick architecture, a perimeter wall, production in metal, shell and stone, and relations with the Omani interior.',
      },
      {
        type: 'p',
        text: 'In more recent years, the Bologna research has continued on several fronts. At Ra’s al-Hadd, the investigations at HD-1 have deepened understanding of the role of the eastern Omani coast in the maritime networks of the 3rd millennium BCE; in the HD-7 necropolis, the excavations are clarifying aspects of the Hafit and Umm an-Nar funerary traditions. At Al-Khutm, a UNESCO site, the University of Bologna is investigating a monumental Bronze Age tower, now better understood thanks to the excavation of the external structures and to 3D digital documentation.',
      },
      {
        type: 'p',
        text: 'A more recent strand within the Bologna research is represented by the Italian Anthropological Mission for the Heritage of the Arabian Peninsula, directed by Eugenio Bortolini and Stefano Benazzi. The project integrates archaeological excavation, 3D modelling, and osteological, isotopic and proteomic analyses. At Halban, in the southern Batinah region, the mission studies monumental Bronze Age tombs dated between the Hafit and Umm an-Nar periods. At the Romail shelter, between the Wahiba Sands and the eastern Hajar mountains, the research has instead identified a stratified sequence with lithic tools, hearths, faunal and plant remains, perforated shells, ochre and rock art: important data for understanding the transitional phases between the Final Palaeolithic and the Neolithic in Oman.',
      },
      {
        type: 'p',
        text: 'Alongside the planned excavations, mention should also be made of the Italian commitment to preventive and rescue-archaeology projects, fundamental for reducing the impact of modern infrastructure on the archaeological heritage. In almost fifty years of activity, the research of the University of Bologna has helped to reconstruct the role of Oman between south-eastern Arabia, Mesopotamia, Iran and the Indus Valley.',
      },
    ],
  },
  {
    id: 'current-excavations',
    number: '05',
    kicker: 'On the ground today',
    title: 'The current UniBo excavations in Arabia',
    blocks: [
      { type: 'h', text: 'Ras al-Hadd' },
      {
        type: 'p',
        text: 'At the coastal locality of Ra’s al-Hadd, at the eastern tip of the Arabian Peninsula, the University of Bologna has for over thirty years conducted archaeological research dedicated to Bronze Age communities. Current investigations focus above all on the HD-7 necropolis, connected to the HD-6 settlement and dated to the 3rd millennium BCE.',
      },
      {
        type: 'p',
        text: 'The excavations have brought to light circular stone tombs, organised in small groups on the rocky terraces behind the beach south of the village. Architecturally, some structures display features typical of the region, such as the outermost wall courses built with white blocks of sedimentary rock gathered along the coast. The burials have yielded human remains, ornaments — above all shell and various kinds of stone — lithic tools and pottery, offering new information on funerary rituals and on the symbolic meaning of the materials used.',
      },
      {
        type: 'p',
        text: 'The research integrates stratigraphic excavation, 3D digital survey, GIS and bioarchaeological analyses, contributing to the reconstruction of the social and cultural transformations of Oman’s coastal communities during the Bronze Age.',
      },
      { type: 'h', text: 'Khutm' },
      {
        type: 'p',
        text: 'The site of Al-Khutm, in the Bat area, is part of Oman’s UNESCO heritage together with Bat and al-Ayn. Here the University of Bologna is investigating a monumental Bronze Age tower, built between the end of the 3rd and the beginning of the 2nd millennium BCE and which until a few years ago was almost invisible, covered by metres of collapse and sediment. The excavations have revealed a circular building about 20 metres in diameter, preserved to a height of several metres, with corridors, internal rooms, articulated entrances and a central well. Ongoing research is helping to clarify the tower’s various construction phases and the relationship between the monumental building, the surrounding structures and the landscape of the Bat oasis.',
      },
      {
        type: 'p',
        text: 'The study of the materials (pottery, stone and metal artefacts) indicates a long occupation between the Umm an-Nar and Wadi Suq phases.',
      },
      {
        type: 'p',
        text: 'The fieldwork combines archaeological excavation, photogrammetric documentation and 3D modelling, with the aim of deepening knowledge of the site and making it more accessible to the public.',
      },
      { type: 'h', text: 'Halban' },
      {
        type: 'p',
        text: 'The archaeological excavation project is conducted by the University of Bologna in collaboration with the Ministry of Heritage and Tourism of the Sultanate of Oman, with the ultimate aim of creating a visitable archaeological park. The Early Bronze Age necropolis of Halban occupies a geographically and strategically crucial position in Oman, located about 35 kilometres west of the capital Muscat. The site rises on a high coastal terrace of limestone origin, positioned precisely between the fertile Al-Batinah coastal plain and the majestic Al-Hajar al-Gharbi mountain range. It stands out for the excellent state of preservation of its structures and for its exceptional visibility over the territory, having already acted in the past as a point of communication between the inland valleys and the coastal communities. The necropolis comprises 33 monumental stone funerary structures with differing structural characteristics: some tombs display the architecture of the Hafit culture (c. 3100–2700 BCE), while others seem to attest to the architectural and ritual evolution or transition towards the more complex forms typical of the subsequent Umm an-Nar period (c. 2700–2000 BCE).',
      },
      {
        type: 'p',
        text: 'Extensive fieldwork, begun in 2023 and still active, has focused on the in-depth exploration of three burials, designated HAL016, HAL021 and HAL025. The burials have been the subject of archaeological, topographic and digital documentation, biomolecular analysis of the osteological remains and typological study of the grave goods. Systematic digital photogrammetric documentation was carried out for all excavation phases. Through Structure-from-Motion (SfM) algorithms, the aerial and terrestrial frames were processed to generate very-high-resolution orthophotomosaics and accurate three-dimensional models of the tombs (such as those of burials HAL016 and HAL021 at the end of excavation).',
      },
      {
        type: 'p',
        text: 'Owing to the severe taphonomic processes and the harsh environmental conditions of the limestone terrace, the skeletal remains recovered within the funerary deposits were extremely fragmented and degraded, making it impossible to apply macroscopic anthropological methods. To overcome this, the researchers adopted a cutting-edge bioarchaeological approach based on the proteomic analysis of amelogenin, a dental-enamel protein encoded on the sex chromosomes in different forms (X and Y). For tomb HAL021, where macroscopic observation of the enamel and dental wear generically indicated only two individuals (an adult and a non-adult), molecular analysis identified the presence of an adult man, an adult woman and a young girl. Strontium isotope analysis of the dental enamel allows the mobility of people to be observed: in the case of HAL021 the man and the girl were local, while the woman had very different values.',
      },
      {
        type: 'p',
        text: 'This was further underlined by the results of the study of the grave goods, with the identification of two carnelian necklace beads and three segmented tubular beads of blue-green and whitish-yellow faience that show close parallels with the productions of the Indus Valley Civilisation dating to Harappa Period 3 (Pakistan). The study attests to the integration of the Halban community into a dense continental network of trade and people. The objects found in HAL025 highlighted the continuity and later reuse of the area in subsequent periods, yielding three copper rings mixed with Islamic-period pottery fragments.',
      },
    ],
  },
  {
    id: 'credits',
    number: '00',
    kicker: 'Colophon',
    title: 'Credits & acknowledgements',
    credits: [
      { role: 'Scientific lead', names: ['Eugenio Bortolini'] },
      { role: 'Coordination', names: ['Vittoria Bianchi'] },
      { role: 'Texts', names: ['Amanda Antonelli', 'Vittoria Bianchi', 'Francesca Barchiesi'] },
      { role: 'Design & graphics', names: ['Benedetta Gaeta'] },
      { role: 'Web design', names: ['Antonios Koutroumpas'] },
      { role: 'Social & communication', names: ['Simone Rizzuto'] },
      { role: 'Photography', names: ['Adam Al-Ghafry', 'Fahad'] },
      { role: '3D models', names: ['Sara Facciani', 'Enzo Cocca'] },
      { role: 'Translations', names: ['Theodore Sheehan'] },
    ],
    acknowledgements:
      'With thanks to ISMEO, the University of Bologna and Biblioteca Salaborsa.',
  },
];
