// Regenerates app/[locale]/research/covers.ts from the cover screenshots
// present in public/images/books/. Run after adding or removing a cover:
//   node scripts/gen-covers.mjs
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'public/images/books';
const slugs = readdirSync(dir)
  .filter((f) => /\.(jpg|jpeg|png|webp)$/i.test(f))
  .map((f) => f.replace(/\.[^.]+$/, ''))
  .sort();

const out =
  '// AUTO-GENERATED by scripts/gen-covers.mjs — do not edit by hand.\n' +
  '// Lists the book slugs that have a real cover screenshot in\n' +
  '// public/images/books/. Re-run `node scripts/gen-covers.mjs` after\n' +
  '// adding or removing a cover.\n\n' +
  'export const COVERS = new Set<string>([\n' +
  slugs.map((s) => `  ${JSON.stringify(s)},`).join('\n') +
  (slugs.length ? '\n' : '') +
  ']);\n';

writeFileSync(join('app/[locale]/research', 'covers.ts'), out);
console.log(`Wrote covers.ts with ${slugs.length} cover(s):`, slugs.join(', ') || '(none)');
